management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, info" # 指定暴露可公开访问的端点
      #允许跨域访问
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always